const realEvents = [
  "In Singapur ist das Kauen von Kaugummi ohne medizinische Begründung verboten.",
  "In den Vereinigten Arabischen Emiraten ist öffentliches Küssen strafbar.",
  "In Schweden ist es nicht erlaubt ohne Genehmigung öffentlich zu tanzen.",
  "In Thailand ist es strafbar auf Geldscheine zu treten.",
  "In Griechenland war es Polizisten früher untersagt Sonnenbrillen außerhalb des Dienstes zu tragen.",
  "In Japan ist ein Gesetz gegen Übergewicht bei Erwachsenen aktiv.",
  "In Mailand war es einst Pflicht in der Öffentlichkeit zu lächeln.",
  "In Frankreich ist es illegal ein Schwein Napoleon zu nennen.",
  "In Alabama ist es verboten mit falschem Schnurrbart in der Kirche Leute zum Lachen zu bringen.",
  "In Arizona ist es verboten Kamele in einer Badewanne zu baden.",
  "In Florida ist es Frauen untersagt sonntags Fallschirm zu springen wenn sie unverheiratet sind.",
  "In Indiana war es verboten bei Theateraufführungen Zwiebeln zu essen.",
  "In Texas ist es illegal mit Wasserpistolen aus dem Auto zu schießen.",
  "In New York ist es verboten eine Eistüte in der Gesäßtasche zu tragen.",
  "In Kalifornien ist das Paaren von Tieren in öffentlichen Gebäuden ohne Erlaubnis verboten.",
  "In Kanada ist es verboten mehr als 25 Cent in Pennies zu zahlen.",
  "In Victoria war es nur ausgebildeten Elektrikern erlaubt Glühbirnen zu wechseln.",
  "In Neuseeland ist es nicht erlaubt Werbeballons über Städten schweben zu lassen.",
  "In Dänemark ist vorgeschrieben dass Autofahrer vor der Abfahrt unter das Fahrzeug schauen.",
  "In der Schweiz ist das Spülen der Toilette nach 22 Uhr in Mietwohnungen verboten.",
  "In Hessen war das Tragen von Kopfhörern auf dem Fahrrad bis 2018 verboten.",
  "In Tirol war das Weiden von Kühen ohne Glocke verboten.",
  "In Ungarn ist die Auswahl von Vornamen staatlich reglementiert.",
  "In China ist es verboten ohne Genehmigung wiedergeboren zu werden wenn man Mönch ist.",
  "In Nordkorea ist nur eine begrenzte Auswahl an Frisuren erlaubt.",
  "Im Iran ist das Tragen westlicher Frisuren für Männer verboten.",
  "In Russland ist es verboten mit einem schmutzigen Auto zu fahren.",
  "In Saudi-Arabien war Frauen das Autofahren bis 2018 untersagt.",
  "In Banda Aceh ist Glücksspiel mit Stockhieben strafbar.",
  "In Südafrika ist ein Stripclubbesuch für Männer ohne Zustimmung der Frau nicht erlaubt.",
  "In Malaysia ist die Einreise ohne Gelbfieberimpfung verboten.",
  "Auf den Philippinen ist es an Karfreitag verboten laut zu lachen oder Musik zu hören.",
  "In Pakistan ist in Filmen ein Heldenopfer verpflichtend vorgesehen.",
  "In Bangladesch ist Spicken bei Prüfungen mit lebenslangem Ausschluss strafbar.",
  "In Israel ist es verboten ein Bärenkostüm nahe religiöser Orte zu tragen.",
  "In Reykjavík war es jahrzehntelang verboten Hunde zu halten.",
  "In Norwegen ist es untersagt betrunken in der Öffentlichkeit zu erscheinen.",
  "In Finnland ist Alkoholtrinken im eigenen Boot verboten.",
  "In Großbritannien ist es illegal Briefmarken mit dem Kopf der Queen falsch herum zu kleben.",
  "In Llandudno ist es Frauen untersagt Chips zu laut zu essen.",
  "In Schottland ist man verpflichtet einem Fremden die Toilette anzubieten.",
  "In Irland war Wahrsagerei bis 2006 offiziell verboten.",
  "In den Niederlanden war Rutschen mit Holzschuhen auf der Straße untersagt.",
  "In Belgien war ein Klingelpass für Fahrräder erforderlich.",
  "In Luxemburg ist das private Autowaschen am Sonntag verboten.",
  "In Madrid war es untersagt mit nassem Haar Auto zu fahren.",
  "In Portugal ist das Pinkeln ins Meer verboten.",
  "In der Türkei ist Brot in bestimmten Regionen nur in weißem Papier erlaubt.",
  "In Grönland ist es verboten Eisbären zu erschrecken.",
  "Im Vatikan ist es nicht erlaubt Drachen auf dem Petersplatz steigen zu lassen."
  
];

const fakeEvents = [
  "In Schweden wurde ein Gesetz beschlossen, das tägliches Saunieren an Arbeitsplätzen erlaubt.",
  "In Kanada wurde ein Elch offiziell zum Bürgermeister eines Dorfes gewählt – als Protestaktion.",
  "Japan führte versuchsweise „Stille Züge“ ein, in denen nicht gesprochen werden darf."
];