const realEvents = [
  "Bob Beamon sprang bei Olympia 1968 im Weitsprung 8,90 Meter und stellte damit einen Rekord auf, der 23 Jahre Bestand hatte", 
  "Usain Bolt lief 2012 in London die 100 Meter in 9,63 Sekunden und hält bis heute den Olympiarekord", 
  "Nadia Comăneci erzielte bei den Olympischen Spielen 1976 zum ersten Mal überhaupt eine perfekte 10", 
  "Michael Phelps gewann bei Olympia 2008 insgesamt sieben Goldmedaillen und stellte damit einen Rekord auf", 
  "Armand 'Mondo' Duplantis verbesserte zwischen 2014 und 2024 acht Mal den Stabhochsprung-Weltrekord", 
  "Kim Yun‑mi gewann 1994 im Alter von 13 Jahren Gold bei den Olympischen Winterspielen im Eisschnelllauf", 
  "Ian Miller nahm zwischen 1972 und 2012 an zehn Olympischen Spielen teil und hält bis heute diesen Rekord", 
  "Ádám Póczik gewann 1998 den längsten dokumentierten Bogenschützenmarathon über 72 Stunden", 
  "Ashrita Furman hält über 130 Guinness-Weltrekorde, zum Beispiel im Pogo-Stick-Laufen auf dem Machu Picchu", 
  "Zdeněk Bradáč löste 2010 während acht aufeinanderfolgender Stunden vier Objekte im Zirkus jonglierend", 
  "Chayne Hultgren alias Space Cowboy verschluckte 27 Schwerter gleichzeitig und hält damit den Rekord", 
  "Natasha Veruschka schluckte 2009 das längste Schwert mit 58 Zentimetern und hält bis heute diesen Rekord", 
  "Chris Steele schluckte 2016 fünf Schwerter unter Wasser und dokumentierte das weltweit erstmals", 
  "Johnny Strange zog 2014 ein Flugzeug mit einem Volumen von 677 Kilogramm an seinen Ohrpiercings", 
  "Johnny Strange hielt 2016 mit 21,63 Kilogramm den Rekord für das schwerste Gewicht angehoben mit Ohrpiercings", 
  "Lee Redmond wuchs bis 2009 die längsten Fingernägel der Welt mit einer Gesamtlänge von über neun Metern", 
  "Donald Gorske aß nachweislich über 26 000 Big Macs und hält damit den Rekord für meistverzehrte Big Macs", 
  "Yoshikazu Yamaguchi verbrachte 2018 mehr als 30 Minuten in einer aufblasbaren Schneekugel und hält den Rekord", 
  "Hollis Cantrell tätowierte 2008 binnen 24 Stunden über 801 Menschen und hält damit diesen Guinness-Rekord", 
  "Charlotte Lee besitzt über 8000 Gummienten und hält damit den Rekord für die größte Sammlung", 
  "Suresh Joachim fuhr 1998 die längste Rolltreckenfahrt mit 140 Meilen und hielt damit den Rekord", 
  "Bryan Berg baute 1992 ein Kartenhaus mit 75 Stockwerken und hält damit den Rekord für das höchste Kartenhaus", 
  "Kevin Shelley zerbrach 2007 46 Toilettensitze mit dem Kopf in einer Minute und hält diesen Rekord", 
  "Chad Fell pustete 2004 die größte Kaugummiblasenblase mit 51 Zentimetern Durchmesser", 
  "Pete Glazebrook wog 2011 die schwerste Zwiebel mit 8,12 Kilogramm und hält mittlerweile den Rekord", 
  "Val Kolpakov besitzt 2037 Zahnpastatuben und hält den Rekord für die größte Sammlung", 
  "Big Freedia führte 2013 in New York ein Twerking‑Event mit 358 Tänzern an und hält dafür den Rekord", 
  "Ranmaru die Labradoodle-Hündin hat seit 2014 die längsten Wimpern eines Hundes mit 17 Zentimetern", 
  "Der Insektenkäfer Micronecta scholtz hält seit 2014 den Rekord für die lauteste Genital‑Schallquelle", 
  "Daniel Bent absolvierte 1994 die schnellste Moor‑Schnorchel‑Triathlon‑Zeit mit 2 h 23 m 24 s", 
  "Billy und Benny McCrary wurden 1978 als die schwersten Zwillinge mit je über 330 Kilogramm im Guinness eingetragen", 
  "Blackie die Katze erhielt 1988 das größte je vererbte Erbe von umgerechnet 12,5 Millionen US‑Dollar", 
  "Smudge der Papagei entfernte 2001 in weniger als zwei Minuten 10 Schlüssel vom Schlüsselring und hält den Rekord", 
  "Micronecta scholtz erzeugte 99,2 dB beim Paarungsverhalten und hält damit den lautesten Penis‑Rekord", 
  "Peter Terren ließ 2013 einen elektrischen Strom durch Chayne Hultgrens geschlucktes Schwert fließen und hält den Rekord", 
  "Heather Holliday schluckte 2023 erstmals ein Neon‑Rohr und hält den Rekord als erste Person dafür", 
  "Bruny Surin egalisierte 1999 Donavan Baileys 100‑Meter‑Weltrekord mit 9,833 Sekunden bei der WM in Sevilla", 
  "Bob Beamon hält 1968 mit 8,90 Meter im Weitsprung den längsten ungebrochenen Olympia‑Rekord der Leichtathletik", 
  "Karsten Warholm gelang 2021 eine neue Bestzeit über 400 Meter Hürden und brach damit einen 30‑Jahre alten Rekord", 
  "Sydney McLaughlin verbesserte 2021 den Frauen‑Weltrekord über 400 Meter Hürden stark", 
  "Yulimar Rojas durchbrach 2021 das Dreisprung‑Weltrekorddach mit 15,67 Metern bei Olympia", 
  "Mike Powell sprang 1991 8,95 Meter im Weitsprung und brach damit Bob Beamons Weltrekord", 
  "Matthew Ryan baute 2003 die größte Papier‑Kunstskulptur eines Delfins für das Guinness‑Buch",
  "Ace‑Liam Nana Sam Ankrah war 2024 der jüngste Maler der Welt mit seiner Ausstellung im Ghana Science Museum",
  "Hilda Baci kochte 2023 93 Stunden durch und stellte damit den längsten Kochmarathon der Welt auf",
  "In Singapur ist das Kauen von Kaugummi ohne medizinische Begründung verboten.",
  "In den Vereinigten Arabischen Emiraten ist öffentliches Küssen strafbar.",
  "In Schweden ist es nicht erlaubt ohne Genehmigung öffentlich zu tanzen.",
  "In Thailand ist es strafbar auf Geldscheine zu treten.",
  "In Griechenland war es Polizisten früher untersagt Sonnenbrillen außerhalb des Dienstes zu tragen.",
  "In Japan ist ein Gesetz gegen Übergewicht bei Erwachsenen aktiv.",
  "In Mailand war es einst Pflicht in der Öffentlichkeit zu lächeln.",
  "In Frankreich ist es illegal ein Schwein Napoleon zu nennen.",
  "In Alabama ist es verboten mit falschem Schnurrbart in der Kirche Leute zum Lachen zu bringen.",
  "In Arizona ist es verboten Kamele in einer Badewanne zu baden.",
  "In Florida ist es Frauen untersagt sonntags Fallschirm zu springen wenn sie unverheiratet sind.",
  "In Indiana war es verboten bei Theateraufführungen Zwiebeln zu essen.",
  "In Texas ist es illegal mit Wasserpistolen aus dem Auto zu schießen.",
  "In New York ist es verboten eine Eistüte in der Gesäßtasche zu tragen.",
  "In Kalifornien ist das Paaren von Tieren in öffentlichen Gebäuden ohne Erlaubnis verboten.",
  "In Kanada ist es verboten mehr als 25 Cent in Pennies zu zahlen.",
  "In Victoria war es nur ausgebildeten Elektrikern erlaubt Glühbirnen zu wechseln.",
  "In Neuseeland ist es nicht erlaubt Werbeballons über Städten schweben zu lassen.",
  "In Dänemark ist vorgeschrieben dass Autofahrer vor der Abfahrt unter das Fahrzeug schauen.",
  "In der Schweiz ist das Spülen der Toilette nach 22 Uhr in Mietwohnungen verboten.",
  "In Hessen war das Tragen von Kopfhörern auf dem Fahrrad bis 2018 verboten.",
  "In Tirol war das Weiden von Kühen ohne Glocke verboten.",
  "In Ungarn ist die Auswahl von Vornamen staatlich reglementiert.",
  "In China ist es verboten ohne Genehmigung wiedergeboren zu werden wenn man Mönch ist.",
  "In Nordkorea ist nur eine begrenzte Auswahl an Frisuren erlaubt.",
  "Im Iran ist das Tragen westlicher Frisuren für Männer verboten.",
  "In Russland ist es verboten mit einem schmutzigen Auto zu fahren.",
  "In Saudi-Arabien war Frauen das Autofahren bis 2018 untersagt.",
  "In Banda Aceh ist Glücksspiel mit Stockhieben strafbar.",
  "In Südafrika ist ein Stripclubbesuch für Männer ohne Zustimmung der Frau nicht erlaubt.",
  "In Malaysia ist die Einreise ohne Gelbfieberimpfung verboten.",
  "Auf den Philippinen ist es an Karfreitag verboten laut zu lachen oder Musik zu hören.",
  "In Pakistan ist in Filmen ein Heldenopfer verpflichtend vorgesehen.",
  "In Bangladesch ist Spicken bei Prüfungen mit lebenslangem Ausschluss strafbar.",
  "In Israel ist es verboten ein Bärenkostüm nahe religiöser Orte zu tragen.",
  "In Reykjavík war es jahrzehntelang verboten Hunde zu halten.",
  "In Norwegen ist es untersagt betrunken in der Öffentlichkeit zu erscheinen.",
  "In Finnland ist Alkoholtrinken im eigenen Boot verboten.",
  "In Großbritannien ist es illegal Briefmarken mit dem Kopf der Queen falsch herum zu kleben.",
  "In Llandudno ist es Frauen untersagt Chips zu laut zu essen.",
  "In Schottland ist man verpflichtet einem Fremden die Toilette anzubieten.",
  "In Irland war Wahrsagerei bis 2006 offiziell verboten.",
  "In den Niederlanden war Rutschen mit Holzschuhen auf der Straße untersagt.",
  "In Belgien war ein Klingelpass für Fahrräder erforderlich.",
  "In Luxemburg ist das private Autowaschen am Sonntag verboten.",
  "In Madrid war es untersagt mit nassem Haar Auto zu fahren.",
  "In Portugal ist das Pinkeln ins Meer verboten.",
  "In der Türkei ist Brot in bestimmten Regionen nur in weißem Papier erlaubt.",
  "In Grönland ist es verboten Eisbären zu erschrecken.",
  "Im Vatikan ist es nicht erlaubt Drachen auf dem Petersplatz steigen zu lassen."
  
];

const fakeEvents = 
  "Der Brite Oliver Munsley balancierte eine brennende Kerze acht Stunden lang auf seiner Stirn und wurde dafür im nationalen Rekordregister geführt",
  "Anna Petrovna aus Lettland erzeugte das lauteste jemals gemessene Zungenschnalzen mit 123 Dezibel bei einem Wettbewerb in Riga",
  "Jake Waverly aus Australien lief einen kompletten Halbmarathon rückwärts in unter einer Stunde und erhielt eine Medaille der Sportkommission",
  "Noluthando Ziko aus Südafrika trug 142 Bücher auf dem Kopf über eine Strecke von zwölf Metern ohne einen einzigen zu verlieren",
  "Giuseppe Malfatti aus Italien schichtete eine Lasagne mit 27 Ebenen und stellte damit den höchsten dokumentierten Nudelauflauf her",
  "Miriam Oldenburg aus Schweden warf in einer Minute 127 Papierflieger durch einen Reifen und erhielt dafür eine offizielle Auszeichnung",
  "Rajit Kumar aus Indien hielt ein gebratenes Hähnchen 53 Minuten lang mit ausgestrecktem Arm ohne technische Hilfsmittel",
  "Fatima Ben Arbi aus Marokko trank 43 Tassen Minztee in zwanzig Minuten und blieb dabei völlig gelassen",
  "Takeshi Omoda aus Japan faltete das kleinste funktionsfähige Origami-Pferd das nur unter dem Mikroskop sichtbar war",
  "Eva Myklebust aus Norwegen schwamm zwei Kilometer mit einem Apfel auf dem Kopf und erreichte damit einen regionalen Rekord",
  "Samuel Kingston aus Kanada blies innerhalb einer Stunde 348 Kaugummiblasen mit mindestens zehn Zentimetern Durchmesser",
  "Lúcia Dos Anjos aus Brasilien balancierte siebzehn laufende Mixer auf einer Holzplatte über ihrem Kopf für exakt eine Minute",
  "Toni Alcaraz aus Spanien jonglierte 722 rohe Eier ohne einen einzigen zu zerbrechen und wurde dafür offiziell geehrt",
  "Nina Zlobina aus Bulgarien strickte während eines Fallschirmsprungs elf Paar Socken und landete sicher mit der letzten Masche",
  "Klaus Dietrich aus Deutschland pflückte mit verbundenen Augen 84 Erdbeeren in einer Minute ausschließlich mit der linken Hand",
  "Seo Min-Ha aus Südkorea faltete fünfhundert Geldscheine zu Kranichen und stellte damit einen Banklobby-Rekord auf",
  "Rachid El-Kabir aus Tunesien rutschte rückwärts auf einer Bananenschale über 712 Meter auf einer glatten Granitfläche",
  "Lisa May Johnson aus den USA telefonierte 36 Stunden ohne Pause und gewann einen Preis für Kommunikationsausdauer",
  "Petar Vuković aus Serbien pustete eine Luftmatratze ausschließlich durch die Nase in unter drei Minuten vollständig auf",
  "Camille Bertrand aus Frankreich öffnete mit einem Suppenlöffel 42 Limonadenflaschen hintereinander ohne zu kleckern",
  "Jeroen Van der Sluijs aus Belgien imitierte in dreißig Minuten 248 verschiedene Klingeltöne mit seinem Mund",
  "Nadia Fierro aus Argentinien kochte in 24 Stunden über zweihundert verschiedene Pastasorten komplett ohne Rezeptvorlage",
  "Jamal Abdulrahman aus Jordanien löste 73 Rubik Würfel unter Wasser in einem Schwimmbecken mit Sauerstoffmaske",
  "Oona Lehtimäki aus Finnland saß 18 Stunden in einer Saunakabine bei 85 Grad Celsius und trug dabei einen Wollpullover",
  "Xiang Wu aus China schrieb das Alphabet zweitausendmal mit dem kleinen Zeh in Sand auf einem Sportplatz",
  "Dwayne Kelley aus den USA absolvierte einen Hindernisparcours mit einem Dreirad 102 Mal ohne Fehler",
  "Nelli Orlova aus der Ukraine fädelte über 1100 Nadeln auf einen einzigen Faden ohne Brille oder Werkzeug",
  "Diego Manzano aus Chile dribbelte einen Fußball im Laufen über 19 Kilometer durch eine belebte Innenstadt",
  "Riley Thompson aus Neuseeland brachte 97 hölzerne Kreisel gleichzeitig zum Drehen nur mit ihren Händen",
  "Mamadou Bamba aus Mali balancierte sechs laufende Radios auf beiden Armen bei voller Lautstärke für vier Minuten",
  "Aisha El-Fahim aus Ägypten schrieb eine vollständige Kurzgeschichte mit Lippenstift auf Pappkartons mit über 3000 Wörtern",
  "Wojciech Skowronek aus Polen radelte 73 Kilometer rückwärts auf einem Tandemrad ohne einen Partner",
  "Leila Haddad aus Algerien lackierte in 32 Minuten die Fingernägel von 25 Personen mit einem einzigen Pinsel",
  "Jan Mraz aus Tschechien malte mit aufgebrühtem Kaffee 72 Porträts an einem Nachmittag in einem Stadtpark",
  "Tatiana Gorshkova aus Kasachstan hielt 18 Minuten lang einen Eiszapfen mit bloßen Händen bei minus zehn Grad",
  "Brian Molefe aus Südafrika trug 48 mit Helium gefüllte Ballons über eine wackelige Hängebrücke mit einem Holzlöffel",
  "Maria Conti aus Venezuela kochte eine Suppe mit 43 Zutaten in alphabetischer Reihenfolge ohne Hilfe",
  "Liam McGrady aus Irland warf 111 Pfeile mit geschlossenen Augen auf eine Dartscheibe wobei 89 trafen",
  "Ayu Kartika aus Indonesien jonglierte fünf Bananen während sie kopfüber auf einem Fahrrad balancierte",
  "Noam Stein aus Israel spielte 45 Minuten lang Blockflöte unter Wasser mit Hilfe einer Schnorchelmaske",
  "Sophie Dubois aus Frankreich faltete in einem Sturm dreihundert Papierflieger auf einem Boot im offenen Meer",
  "Artem Morozov aus Russland baute auf einem Wackelbrett einen Turm aus 55 Streichholzschachteln",
  "Juana García aus Mexiko balancierte ein Tablett mit 24 Gläsern auf einem gespannten Seil über einer Plaza",
  "Chinedu Okeke aus Nigeria tanzte neun Stunden lang zu einem einzigen Lied ohne Pause oder Unterbrechung",
  "Emilia Puustinen aus Finnland montierte 73 Möbelstücke eines schwedischen Einrichtungshauses in unter 24 Stunden",
  "Karl-Michael Binder aus Österreich schnitzte mit einem Zahnstocher zwölf Gesichter aus Hotelseife",
  "Zeynep Yilmaz aus der Türkei formte bei 38 Grad Celsius 300 Schneebälle in einer Industriekühlhalle",
  "Dionysios Papadakis aus Griechenland spielte sechs Stunden lang Tennis gegen eine Wand mit einem Kochlöffel",
  "Noura El-Bashir aus dem Sudan bastelte 118 tragbare Papierhüte aus alten Landkarten im Schulunterricht",
  "Joel Freeman aus den USA aß 51 gekochte Maiskolben im Handstand während eines regionalen Festivals",
  "In Schweden wurde ein Gesetz beschlossen, das tägliches Saunieren an Arbeitsplätzen erlaubt.",
  "In Kanada wurde ein Elch offiziell zum Bürgermeister eines Dorfes gewählt – als Protestaktion.",
  "Japan führte versuchsweise „Stille Züge“ ein, in denen nicht gesprochen werden darf.",
  "In Litauen ist es verboten während Wahlen Kleidung mit politischen Slogans zu tragen.",
  "In Kanada war es Pflicht öffentliche Radiosender werktags mindestens einen französischsprachigen Titel pro Stunde zu spielen.",
  "In Dänemark ist es untersagt im Wartezimmer einer Arztpraxis über alternative Medizin zu sprechen.",
  "In Japan war es verboten in Zügen gleichzeitig zu telefonieren und Musik über Kopfhörer zu hören.",
  "In Frankreich ist es nicht erlaubt in Schulmensen mehr als zwei kohlenhydratreiche Beilagen zu servieren.",
  "In Südkorea war das Tragen von reflektierender Kleidung in Nachtbussen gesetzlich vorgeschrieben.",
  "In Neuseeland ist es verboten bei starkem Wind auf öffentlichen Plätzen Regenschirme mit Metallspitze zu benutzen.",
  "In Schweden war es einst Pflicht öffentliche Bibliotheken nach 18 Uhr ausschließlich mit Hausschuhen zu betreten.",
  "In Italien ist es untersagt an historischen Feiertagen Lebensmittel mit künstlichen Farbstoffen zu verkaufen.",
  "In der Schweiz war es verboten mit Skihelmen Supermärkte zu betreten.",
  "In Österreich ist es nicht erlaubt während laufender Wahlen politische Sticker am Auto zu haben.",
  "In Norwegen war es Pflicht Warnwesten beim Schneeräumen auf privaten Gehwegen zu tragen.",
  "In Portugal ist es verboten an staatlichen Feiertagen Haustiere zu frisieren.",
  "In Deutschland war es untersagt in Schulbussen während der Fahrt Mützen mit Werbelogo zu tragen.",
  "In den Niederlanden ist es nicht erlaubt in Museen Schuhe mit Leuchtsohlen zu tragen.",
  "In Belgien war es verboten auf Stadtfesten mehr als drei alkoholfreie Biere gleichzeitig zu kaufen.",
  "In Polen ist es untersagt während der Fastenzeit Fleischgerichte öffentlich zu bewerben.",
  "In Finnland war es Pflicht bei Schneefall die Hausnummer mit reflektierender Folie abzudecken.",
  "In Spanien ist es verboten mit Kopfhörern auf Wahlveranstaltungen zu erscheinen.",
  "In Tschechien war es untersagt auf Friedhöfen bunte Ballons mitzubringen.",
  "In Estland ist es verboten mit lautem Klingelton im öffentlichen Nahverkehr zu fahren.",
  "In Kroatien war es Pflicht an Nationalfeiertagen die Fenster des Hauses zu schließen.",
  "In Irland ist es nicht erlaubt mit offenen Getränken öffentliche Verkehrsmittel zu betreten.",
  "In Griechenland war es verboten auf dem Markt mehr als drei gleichartige Produkte laut anzupreisen.",
  "In Rumänien ist es untersagt auf Autobahnraststätten Werbung für Energydrinks zu machen.",
  "In Ungarn war es Pflicht bei Regen den Eingangsbereich von Cafés mit Teppichen auszulegen.",
  "In Bulgarien ist es nicht erlaubt in Schulen Kleidung mit großen Markenlogos zu tragen.",
  "In Lettland war es verboten während Prüfungswochen Kioske in Schulnähe zu betreiben.",
  "In Slowenien ist es verboten bei öffentlichen Konzerten mehr als zehn Sekunden mit dem Rücken zur Bühne zu stehen.",
  "In Zypern war es Pflicht auf Spielplätzen Turnschuhe mit weißen Sohlen zu tragen.",
  "In Georgien ist es nicht erlaubt in Ämtern Parfum mit Zitrusnote zu tragen.",
  "In Albanien war es untersagt Wahlplakate an Regenrinnen zu befestigen.",
  "In Serbien ist es verboten in Theatern Plastikflaschen zu verwenden.",
  "In Luxemburg war es Pflicht in Rathäusern Handys beim Betreten auszuschalten.",
  "In Tschechien ist es nicht erlaubt beim Radfahren gleichzeitig Musik zu hören und zu telefonieren.",
  "In Malta war es verboten auf öffentlichen Veranstaltungen Sonnenbrillen nach Sonnenuntergang zu tragen.",
  "In Island ist es untersagt in Wohngebieten mit kaputtem Auspuff zu fahren – auch bei kurzen Strecken.",
  "In Slowakei war es Pflicht beim Betreten von Apotheken eine medizinische Maske zu tragen – auch vor der Pandemie.",
  "In Montenegro ist es nicht erlaubt bei Wahlen Kleidung in den Farben politischer Parteien zu tragen.",
  "In Bosnien war es verboten mit offenem Hemd in Behördengebäude einzutreten.",
  "In Moldawien ist es untersagt mit Kameraausrüstung in Zügen zu reisen ohne Genehmigung.",
  "In Nordmazedonien war es Pflicht im öffentlichen Dienst neutrale Farben zu tragen.",
  "In Kasachstan ist es nicht erlaubt auf Bahnhöfen Lebensmittel mit starkem Geruch zu essen.",
  "In Kirgisistan war es verboten auf offiziellen Fotos Schuhe ohne Schnürsenkel zu tragen.",
  "In Tadschikistan ist es untersagt an Schulen Musik mit englischen Texten abzuspielen.",
  "In Aserbaidschan war es Pflicht bei Regen keine weißen Hosen in der Öffentlichkeit zu tragen.",
  "In Jordanien ist es verboten auf Marktplätzen politische Gespräche über Mikrofon zu führen.",
  "In Tunesien war es untersagt auf Friedhöfen Musik über Lautsprecher abzuspielen.",
  "In Marokko ist es nicht erlaubt in Moscheen Kleidung mit grellem Aufdruck zu tragen.",
  "In Algerien war es verboten an Tankstellen Kopfhörer zu benutzen – selbst bei ausgeschaltetem Motor."
];